### ISSUE TITLE
broken link to CDT submodule

### ISSUE THREAD

**Issue by district10** [artem-ogre/PythonCDT#2]
<img width="971" alt="image" src="https://github.com/artem-ogre/PythonCDT/assets/5262037/a45b9eba-6542-4e77-a988-d89f9fc58322">

Branch not pushed? Or deleted after merging?

**Comment by artem-ogre** [comment]
Thanks, I will fix it.

**Comment by artem-ogre** [comment]
Reminder to myself: try to add a tag at the dangling commit, hopefully the issue will get solved.

**Comment by artem-ogre** [comment]
I made a branch at the commit, will do for now. Please let me know if you have any feedback/suggestions.
